---
- name: Vagrant Ansible Sample
  hosts: all
  user: vagrant
  vars:
    mysql_root_password: ''
    rbenv_ruby_version: 2.3.1
    rbenv_gems:
      - bundler
      - rubocop
    nodejs_npm_global_packages:
      - name: jslint
      - name: node-sass
      - name: phantomjs
      - name: purify-css
      - name: strip-css-comments-cli
      - name: n
    zsh_ohmy_plugins:
      - git
      - git-flow
      - docker
      - rails

  tasks:
    - name: update node to latest version
      become: yes
      shell: |
        n latest
        npm update -g npm

    - name: install packages
      become: yes
      apt: name={{item}} update_cache=yes
      with_items:
        - git
        - nkf
        - build-essential
        - vim-gnome
        - fonts-ipafont
        - libmysqlclient-dev
        - libmagickwand-dev
        - silversearcher-ag
        - libsqlite3-dev

  roles:
    - role: vaulttec.zsh
    - role: joshualund.golang
      become: yes
    - role: spitfast.rbenv
    - role: geerlingguy.nodejs
      become: yes
    - role: geerlingguy.mysql
      become: yes
